/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guibuilder;

import javax.swing.JOptionPane;

/**
 *
 * @author Pedro
 */
public class CadastroPedido extends javax.swing.JFrame {

    /**
     * Creates new form CadastroPedido
     */
    public CadastroPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Acompanhamento = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtBemVindo = new javax.swing.JLabel();
        txtSelecione = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtQuantidade = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JLabel();
        txtPreco = new javax.swing.JLabel();
        txtAcompanhamento = new javax.swing.JLabel();
        txtAdicional = new javax.swing.JLabel();
        btnCadastrarPedido = new javax.swing.JButton();
        fieldQuantidade = new javax.swing.JTextField();
        fieldNomeCliente = new javax.swing.JTextField();
        fieldPreco = new javax.swing.JTextField();
        rbnSim = new javax.swing.JRadioButton();
        rbnNao = new javax.swing.JRadioButton();
        comboAdicional = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        feedbackNome = new javax.swing.JLabel();
        feedbackPreco = new javax.swing.JLabel();
        feedbackQuantidade = new javax.swing.JLabel();
        feedbackAdicional = new javax.swing.JLabel();
        feedbackAcompanhamento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtBemVindo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtBemVindo.setText("Cadastre o Pedido");

        txtSelecione.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSelecione.setText("Preencha todos os campos abaixo:");

        btnSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtBemVindo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSair))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSelecione)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(txtBemVindo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSair)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSelecione)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtQuantidade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtQuantidade.setText("Quantidade");

        txtNomeCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNomeCliente.setLabelFor(txtNomeCliente);
        txtNomeCliente.setText("Nome do Cliente");

        txtPreco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPreco.setLabelFor(txtPreco);
        txtPreco.setText("Preço (R$)");

        txtAcompanhamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAcompanhamento.setText("Acompanhamento");

        txtAdicional.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAdicional.setText("Adicional");

        btnCadastrarPedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCadastrarPedido.setText("Cadastrar");
        btnCadastrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarPedidoActionPerformed(evt);
            }
        });

        fieldNomeCliente.setToolTipText("Digite o nome do cliente neste espaço em branco");

        Acompanhamento.add(rbnSim);
        rbnSim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbnSim.setText("Sim");

        Acompanhamento.add(rbnNao);
        rbnNao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbnNao.setText("Não");

        comboAdicional.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboAdicional.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma opção:", "Não", "Bacon", "Cebola", "Calabresa", "Bife Extra", "Batata Frita", "Catupiry", "4 Queijos" }));
        comboAdicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAdicionalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAcompanhamento, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbnSim)
                        .addGap(18, 18, 18)
                        .addComponent(rbnNao)))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtAdicional, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                        .addGap(226, 226, 226))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(comboAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btnCadastrarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidade)
                    .addComponent(txtPreco)
                    .addComponent(txtNomeCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAcompanhamento)
                    .addComponent(txtAdicional))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbnSim)
                        .addComponent(rbnNao)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btnCadastrarPedido)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {fieldNomeCliente, fieldQuantidade});

        txtNomeCliente.getAccessibleContext().setAccessibleDescription("Campo textual onde está escrito o texto \"Nome do Cliente\"");
        fieldNomeCliente.getAccessibleContext().setAccessibleName("Caixa de Texto para Nome do Cliente");
        fieldNomeCliente.getAccessibleContext().setAccessibleDescription("Caixa de Texto para que o usuário digite o \"Nome do Cliente\"");

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Informações do Pedido");

        feedbackNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        feedbackNome.setText("Nome Cliente: ");

        feedbackPreco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        feedbackPreco.setText("Preço:");

        feedbackQuantidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        feedbackQuantidade.setText("Quantidade:");

        feedbackAdicional.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        feedbackAdicional.setText("Adicional: ");

        feedbackAcompanhamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        feedbackAcompanhamento.setText("Acompanhamento: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(feedbackNome)
                            .addComponent(feedbackPreco)
                            .addComponent(feedbackQuantidade)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(feedbackAdicional))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(feedbackAcompanhamento)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(feedbackNome)
                .addGap(18, 18, 18)
                .addComponent(feedbackPreco)
                .addGap(18, 18, 18)
                .addComponent(feedbackQuantidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(feedbackAcompanhamento)
                .addGap(18, 18, 18)
                .addComponent(feedbackAdicional)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCadastrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarPedidoActionPerformed
        Pedido p = new Pedido();

        try {
            p.setNomeCliente(fieldNomeCliente.getText());

            //Convertendo a String do TextField para um Double
            p.setPreco(Double.parseDouble(fieldPreco.getText()));

            //Convertendo a String do TextField para um Int
            p.setQuantidade(Integer.parseInt(fieldQuantidade.getText()));

            //Manuseando a informação dos RadioButton
            if (rbnSim.isSelected()) {
                p.setAcompanhamento("Sim");
            } else if (rbnNao.isSelected()) {
                p.setAcompanhamento("Não");
            } else {
                p.setAcompanhamento("");
            }

            //Manusear a informação do ComboBox
            if (comboAdicional.getSelectedItem().toString().equalsIgnoreCase("Selecione uma opção:")) {
                p.setAdicional("");
            } else {
                p.setAdicional(comboAdicional.getSelectedItem().toString());
            }
            
            p.setPronto(false);

            if (ListaPedido.adicionar(p)) {
                //JOptionPane.showMessageDialog(null, "Pedido cadastrado com sucesso!");
                feedbackNome.setText("Nome do Cliente: " + p.getNomeCliente());
                feedbackPreco.setText("Preço: " + p.getPreco());
                feedbackQuantidade.setText("Quantidade: " + p.getQuantidade());
                feedbackAdicional.setText("Adicional? " + p.getAdicional());
                feedbackAcompanhamento.setText("Acompanhamento? " + p.getAcompanhamento());
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Pedido não pode ser cadastrado!");
            System.out.println(e); //Dica para o programador ver qual foi o erro e tratar no futuro
        }
    }//GEN-LAST:event_btnCadastrarPedidoActionPerformed

    private void comboAdicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAdicionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAdicionalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Acompanhamento;
    private javax.swing.JButton btnCadastrarPedido;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> comboAdicional;
    private javax.swing.JLabel feedbackAcompanhamento;
    private javax.swing.JLabel feedbackAdicional;
    private javax.swing.JLabel feedbackNome;
    private javax.swing.JLabel feedbackPreco;
    private javax.swing.JLabel feedbackQuantidade;
    private javax.swing.JTextField fieldNomeCliente;
    private javax.swing.JTextField fieldPreco;
    private javax.swing.JTextField fieldQuantidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton rbnNao;
    private javax.swing.JRadioButton rbnSim;
    private javax.swing.JLabel txtAcompanhamento;
    private javax.swing.JLabel txtAdicional;
    private javax.swing.JLabel txtBemVindo;
    private javax.swing.JLabel txtNomeCliente;
    private javax.swing.JLabel txtPreco;
    private javax.swing.JLabel txtQuantidade;
    private javax.swing.JLabel txtSelecione;
    // End of variables declaration//GEN-END:variables
}
