/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guibuilder;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pedro
 */
public class ListaPedidos extends javax.swing.JFrame {

    /**
     * Creates new form ListaPedidos
     */
    public ListaPedidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBemVindo = new javax.swing.JLabel();
        txtSelecione = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        areaTabela = new javax.swing.JPanel();
        areaRolagemTabela = new javax.swing.JScrollPane();
        tabelaPedido = new javax.swing.JTable();
        btnNovoPedido = new javax.swing.JButton();
        btnExcluirPedido = new javax.swing.JButton();
        btnAtualizarPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtBemVindo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtBemVindo.setText("Listagem de Pedidos");

        txtSelecione.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSelecione.setText("Abaixo estão os pedidos do dia:");

        btnSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtBemVindo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                        .addComponent(btnSair))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSelecione)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBemVindo)
                    .addComponent(btnSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSelecione)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tabelaPedido.setModel(montarTabela());
        areaRolagemTabela.setViewportView(tabelaPedido);

        btnNovoPedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNovoPedido.setText("Novo Pedido");
        btnNovoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoPedidoActionPerformed(evt);
            }
        });

        btnExcluirPedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnExcluirPedido.setText("Excluir Pedido");
        btnExcluirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirPedidoActionPerformed(evt);
            }
        });

        btnAtualizarPedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAtualizarPedido.setText("Atualizar Pedido");
        btnAtualizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout areaTabelaLayout = new javax.swing.GroupLayout(areaTabela);
        areaTabela.setLayout(areaTabelaLayout);
        areaTabelaLayout.setHorizontalGroup(
            areaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(areaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(areaRolagemTabela)
                    .addGroup(areaTabelaLayout.createSequentialGroup()
                        .addComponent(btnNovoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnExcluirPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAtualizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        areaTabelaLayout.setVerticalGroup(
            areaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaTabelaLayout.createSequentialGroup()
                .addComponent(areaRolagemTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(areaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoPedido)
                    .addComponent(btnExcluirPedido)
                    .addComponent(btnAtualizarPedido))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(areaTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(areaTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnExcluirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirPedidoActionPerformed
        ListaPedido.excluir(getPosicao());
    }//GEN-LAST:event_btnExcluirPedidoActionPerformed

    private void btnNovoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoPedidoActionPerformed
        CadastroPedido cp = new CadastroPedido();
        cp.setVisible(true);
    }//GEN-LAST:event_btnNovoPedidoActionPerformed

    private void btnAtualizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarPedidoActionPerformed
        int linhaSelecionada = getPosicao();
        
        PedidoPronto pp = new PedidoPronto(linhaSelecionada);
        pp.setLocationRelativeTo(null);
        pp.setVisible(true);
    }//GEN-LAST:event_btnAtualizarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaPedidos().setVisible(true);
            }
        });
    }
    
    
    private DefaultTableModel montarTabela(){
        String[] colunas = {"ID", "Cliente", "Preço", "Quantidade", "Acompanhamento", "Adicional", "Pronto"};
        
        //Criamos a tabela "na mão"
        DefaultTableModel tabela = new DefaultTableModel(colunas, 0);
        
        //Pegar os dados da lista de produtos
        ArrayList<Pedido> lista = ListaPedido.listar();
        
        //FOR para MONTAR A LINHA na tabela
        for (int i = 0; i < lista.size(); i++) {
            Pedido p = lista.get(i);
            
            String pronto = "";
            
            if(p.isPronto()) {
                pronto = "Sim";
            }else {
                pronto = "Não";
            }
            
            String [] linha = {
                Integer.toString(p.getId()),
                p.getNomeCliente(),
                Double.toString(p.getPreco()),
                Integer.toString(p.getQuantidade()),
                p.getAcompanhamento(),
                p.getAdicional(),
                pronto
            };
            tabela.addRow(linha); //Não esquecer de adicionar a linha na tabela!
        }
        
        return tabela;
    }
    
    private int getPosicao(){
        int posicao = tabelaPedido.getSelectedRow();
        
        if(posicao <= -1) {
            JOptionPane.showMessageDialog(null, "Selecione um item para excluir:");
        }
        
        return posicao;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane areaRolagemTabela;
    private javax.swing.JPanel areaTabela;
    private javax.swing.JButton btnAtualizarPedido;
    private javax.swing.JButton btnExcluirPedido;
    private javax.swing.JButton btnNovoPedido;
    private javax.swing.JButton btnSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable tabelaPedido;
    private javax.swing.JLabel txtBemVindo;
    private javax.swing.JLabel txtSelecione;
    // End of variables declaration//GEN-END:variables
}
